sudo: required

services:
  - docker

before_install:
  - docker build -t sariamirza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sariamirza/react-test npm test -- --coverage --watchAll=false

after_success:
  - test $TRAVIS_BRANCH = "master" && docker build -t sariamirza/client-prod ./client
  - test $TRAVIS_BRANCH = "master" && docker build -t sariamirza/api-prod ./server
  - test $TRAVIS_BRANCH = "master" && docker build -t sariamirza/nginx-prod ./nginx
  - test $TRAVIS_BRANCH = "master" && docker build -t sariamirza/worker-prod ./worker
  - test $TRAVIS_BRANCH = "master" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - test $TRAVIS_BRANCH = "master" && docker push sariamirza/client-prod
  - test $TRAVIS_BRANCH = "master" && docker push sariamirza/api-prod
  - test $TRAVIS_BRANCH = "master" && docker push sariamirza/worker-prod
  - test $TRAVIS_BRANCH = "master" && docker push sariamirza/nginx-prod

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-container"
  env: "Multi-container-env"
  bucket_name: "elasticbeanstalk-eu-north-1-058264168537"
  bucket_path: "multi-container"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
