version: "3"

services:
  nginx:
    image: sariamirza/nginx-prod
    restart: always
    ports:
      - 8080:80
    depends_on:
      - postgres
      - redis
    volumes:
      - shared-build:/usr/share/nginx/build
  
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=40884432SARsar123@
      - POSTGRES_DB=demo
      - POSTGRES_HOST_AUTH_METHOD=trust
    
  redis:
    image: "redis:latest"
  
  api:
    image: sariamirza/api-prod
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=demo
      - PGPASSWORD=40884432SARsar123@
      - PGPORT=5432
    depends_on:
      - postgres
      - redis
      - nginx

  worker:
    image: sariamirza/worker-prod
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./worker:/app
      - /app/node_modules
    depends_on:
      - redis

  client:
    image: sariamirza/client-prod
    volumes:
      - shared-build:/app/build
    depends_on:
      - api
      - postgres
      - redis
volumes:
  shared-build: